# sync-claude-to-codex.ps1
# Regenerates AGENTS.md from .claude/agents/ and .claude/skills/
# Run after any change to agent or skill files.

param(
    [string]$RepoRoot = $PSScriptRoot + "\.."
)

$RepoRoot = (Resolve-Path $RepoRoot).Path
$AgentsDir = Join-Path $RepoRoot ".claude\agents"
$SkillsDir = Join-Path $RepoRoot ".claude\skills"
$OutputFile = Join-Path $RepoRoot "AGENTS.md"
$Today = (Get-Date).ToString("yyyy-MM-dd")

function Get-Frontmatter {
    param([string]$FilePath)
    $lines = Get-Content $FilePath -Encoding utf8
    $inFrontmatter = $false
    $yaml = @{}
    $currentKey = $null
    $collectingBlock = $false
    $blockLines = @()

    foreach ($line in $lines) {
        if ($line.Trim() -eq "---" -and -not $inFrontmatter) {
            $inFrontmatter = $true
            continue
        }
        if ($line.Trim() -eq "---" -and $inFrontmatter) {
            # Flush any open block scalar
            if ($collectingBlock -and $currentKey) {
                $yaml[$currentKey] = ($blockLines -join " ").Trim()
            }
            break
        }
        if (-not $inFrontmatter) { continue }

        if ($collectingBlock) {
            # Indented continuation lines belong to the block scalar
            if ($line -match "^  ") {
                $blockLines += $line.Trim()
                continue
            } else {
                # Block ended
                $yaml[$currentKey] = ($blockLines -join " ").Trim()
                $collectingBlock = $false
                $currentKey = $null
                $blockLines = @()
            }
        }

        if ($line -match '^([\w][\w-]*):\s*>\s*$') {
            # YAML folded block scalar — collect following indented lines
            $currentKey = $Matches[1]
            $collectingBlock = $true
            $blockLines = @()
        } elseif ($line -match '^([\w][\w-]*):\s*(.+)$') {
            $key = $Matches[1]
            $val = $Matches[2].Trim().Trim('"')
            $yaml[$key] = $val
        }
    }
    return $yaml
}

$agents = @()
Get-ChildItem -Path $AgentsDir -Filter "*.md" | Sort-Object Name | ForEach-Object {
    $fm = Get-Frontmatter $_.FullName
    if ($fm["name"] -and $fm["description"]) {
        $agents += [PSCustomObject]@{
            Name        = $fm["name"]
            Description = $fm["description"]
        }
    }
}

$skills = @()
Get-ChildItem -Path $SkillsDir -Directory | Sort-Object Name | ForEach-Object {
    $skillFile = Join-Path $_.FullName "SKILL.md"
    if (Test-Path $skillFile) {
        $fm = Get-Frontmatter $skillFile
        $name = $fm["name"]
        if (-not $name) { $name = $_.Name }
        if ($fm["description"]) {
            $skills += [PSCustomObject]@{
                Name            = $name
                Description     = $fm["description"]
                PrimaryAgent    = $fm["primary-agent"]
                InvocationBound = $fm["invocation-boundary"]
            }
        }
    }
}

$out = [System.Collections.Generic.List[string]]::new()
$out.Add("# AGENTS.md - Codex Mirror")
$out.Add("")
$out.Add("> **Do not edit this file manually.** It is a generated mirror of .claude/agents/ and .claude/skills/.")
$out.Add("> Regenerate with: powershell -File scripts/sync-claude-to-codex.ps1")
$out.Add("> The pre-commit hook regenerates it automatically if installed (scripts/install-git-hooks.ps1).")
$out.Add("")
$out.Add("This file exists so that Codex and other tools that cannot read .claude/ directly have access to the full agent and skill surface for this project.")
$out.Add("")
$out.Add("Last generated: $Today")
$out.Add("")
$out.Add("---")
$out.Add("")
$out.Add("## Agents")
$out.Add("")
$out.Add("Agents are role definitions that govern how Claude approaches a category of work.")
$out.Add('Codex should use them as project role guidance: when a task matches an agent description, or the user names an agent, read the authoritative definition in `.claude/agents/<agent>.md` and apply its mission, scope, guardrails, escalation rules, and output contract for that work.')
$out.Add("Codex native sub-agent types are separate from these project roles; these definitions still govern how Codex should reason, implement, review, and report within this repository.")
$out.Add("")
$out.Add("| Agent | Description |")
$out.Add("|---|---|")
foreach ($a in $agents) {
    $out.Add("| $($a.Name) | $($a.Description) |")
}
$out.Add("")
$out.Add("Agent definitions live in .claude/agents/. Each file is the authoritative source for that role.")
$out.Add("")
$out.Add("---")
$out.Add("")
$out.Add("## Skills")
$out.Add("")
$out.Add("Skills encode domain knowledge and governance requirements for specific recurring tasks.")
$out.Add("")
$out.Add("| Skill | Description | Primary Agent | Invocation Boundary |")
$out.Add("|---|---|---|---|")
foreach ($s in $skills) {
    $agent = if ($s.PrimaryAgent) { $s.PrimaryAgent } else { "any" }
    $bound = if ($s.InvocationBound) { $s.InvocationBound } else { "" }
    $out.Add("| $($s.Name) | $($s.Description) | $agent | $bound |")
}
$out.Add("")
$out.Add("Skill definitions live in .claude/skills/<skill-name>/SKILL.md.")

$out | Out-File -FilePath $OutputFile -Encoding utf8

Write-Host "AGENTS.md regenerated: $($agents.Count) agents, $($skills.Count) skills"
