# Local development overrides (Docker Compose)
spring.datasource.url=jdbc:postgresql://db:5432/dcms
spring.datasource.username=dcms
spring.datasource.password=dcms

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/dcms

logging.level.root=debug
logging.level.com.netcompany.dcms=debug
